### ISSUE TITLE
Don't read file from disk on every api request

### ISSUE THREAD

**Issue by matthewrobb** [Howie17/dg-weather#9]
Node.js isn't like PHP or other frameworks where it "spins up" and "spins down" for each request. What this means is you can do very simple things like store data in memory that persists between requests.

Right now every api call reads from disk which is very very poor practice. Instead what needs to happen is that the structure gets read from disk at start up into memory and kept there. You can check against the object as requests come in to see if the data is stale. If the data is stale THEN make the request to the remote api to get new data and put it in memory, return it to the user, THEN persist it to disk.

**Comment by Howie17** [comment]
Are you suggesting I do this for courselist.json (only), since this is being used to see how stale the data is or would this be beneficial to do for the course forecasts as well? I could call a function when the server starts that pulls the current forecasts into their individual course forecast variables, but as the course list grows to 5,000+ that seems like it could be a lot of data.

**Comment by Howie17** [comment]
Adding... 
`let courseList=require('./courselist.json')`

...lets me read from the variable while the server is running, but if a new forecast is pulled and the courselist.json file's lastupdate is changed, the new variable isn't updating placing the same code:

`courseList=require('./courselist.json')` 

...right after the .json file is written to. Is this something unique to require, and I should be using something else?

**Comment by Howie17** [comment]
per http://stackoverflow.com/questions/35389060/read-json-file-content-with-require-vs-fs-readfile, require is synchronous, so once it is read, any other calls to it returns the cached version. That explains it!
